language: node_js
node_js:
  - 12
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
notifications:
  webhooks: https://coveralls.io/webhook
