language: node_js
node_js:
  - 12
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: nyc report --reporter=text-lcov | coveralls
notifications:
  webhooks: https://coveralls.io/webhook
